name: test-gh
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install ytt
      uses: carvel-dev/setup-action@v1
      with:
        only: ytt
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: |
        ./hack/test-all.sh
