name: Update install.sh on Carvel Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - releases.yaml
jobs:
  generate-new-install-sh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install ytt
        uses: carvel-dev/setup-action@v1
        with:
          only: ytt
      - run: |
          set -e -x

          ./scripts/generate_install_sh.sh ./releases.yaml ./tmp/
          mv ./tmp/install.sh.txt ./install.sh
          chmod u+x install.sh
      - name: Upload install.sh
        uses: actions/upload-artifact@v2
        with:
          name: new-install-sh
          path: install.sh
  update-install-sh:
    needs: generate-new-install-sh
    uses: carvel-dev/release-scripts/.github/workflows/commit-and-push.yml@main
    secrets:
      githubDeployPrivateKey: ${{ secrets.INSTALL_SH_DEPLOY_PRIVATE_KEY }}
    with:
      repository: carvel-dev/carvel
      branch: develop
      artifactName: new-install-sh
      artifactPath: ./site/static/
